In [17]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(M)
Final = M*A
print(Final)


[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [29]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])

n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(np.dot(M,b))


[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]
