In [0]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(M)
Final = M*A
print(Final)


[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [0]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])

n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(np.dot(M,b))


[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]


In [0]:
import numpy as np

def Decomposition_LU(a,b):
  n = len(a)
  u = a
  l = np.eye(n)
  
  for k in range(0,n-1):
    for i in range(k+1,n):
        l[i][k] = a [i][k]/a[k][k]
        u[i][k] = 0
        for j in range(k+1, n):
          u[i][j] = u[i][j] - l[i][k]*u[k][j]
          
  return l, u

def resolSystem_TriAdapted(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(0,n):
      s=0
      for j in range(0,n-1):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x
  
def resolSystem_Tri(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(n-2,-1,-1):
      s=0
      for j in range(i+1,n):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x

def all_integrated(a,b):
  print("\nMatriz A: ")
  print(a)
  print("\nSolução de X Pelo Linalg:")
  resp = np.linalg.solve(a,b)
  print(resp)
  l, u = Decomposition_LU(a,b)
  print("\nMatriz L: ")
  print(l)
  print("\nMatriz U: ")
  print(u)
  y = resolSystem_TriL(l,b)
  print("\nLy = b" )
  print("Y=" )
  print(y)
  print("\nUx = y")
  print("X =")
  x_solverSystem = resolSystem_Tri(u,y)
  print(x_solverSystem)


  
  
a = np.array([[3.,(2.),(4.)], [1.,1.,(2.)], [(4.),(3.),(2.)]])
b = np.array([1.,2.,3.])


all_integrated(a,b)




Matriz A: 
[[3. 2. 4.]
 [1. 1. 2.]
 [4. 3. 2.]]

Solução de X Pelo Linalg:
[-3.  5.  0.]

Matriz L: 
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]

Matriz U: 
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -4.        ]]

Ly = b
Y=
[1.0, 1.6666666666666667, -4.440892098500626e-16]

Ux = y
X =
[-3.0, 5.0, 1.1102230246251565e-16]


In [2]:
#Def de cdecomposição LU com pivoteamento (usando exemplo do material)

import numpy as np

def pivoting(a,p,n,b):
  
  print("\nMatriz inicial:")
  print(a)
  
  #pv = pivo
  #p = matriz identidade
  #r = posição em relação ao pivô
  
  for k in range(0,n-1):
    pv = a[k][k]
    r = k

    for i in (k+1,n-1):
      if( abs(a[i][k]) > abs(pv)): # se o módulo de a[i][k] for maior que o módulo do pivô
        pv = a[i][k]
        r = i
    if(pv == 0):
      break
    if(r != k): # Aqui realizamos as trocas de coluna, em relação ao pivô atual, da matriz a, da matriz identidade, da array b
      
      aux = np.copy( p[ k, : ] )
      p[ k, : ] = np.copy( p[ r, : ] )    #Da identidade
      p[ r, : ] = np.copy( aux )
      ''
      aux = np.copy( a[ k, : ] )
      a[ k, : ] = np.copy( a[ r, : ] )  #Da matriz a
      a[ r, : ] = np.copy( aux )
      
      aux = np.copy( b[ k] )
      b[ k] = np.copy( b[ r] )   #De b
      b[ r] = np.copy( aux )      

    cont = 0

    for i in np.arange( k + 1, n ): #Sistema de gauss, normal, visto anteriormente
        m = a[ i, k ] / a[ k, k ]
        a[ i, k ] = m
        for j in np.arange( k + 1, n):
            a[ i, j ] -= m * a[ k, j ]
            
    print("\nMatriz A do pivotemaneto")
    print(a)
  print("\nMatriz identidade Final:")
  print(p)
  print("\nMatriz b Final:")
  print(b)
    
  return a, p, b



#Sistema de decomposição LU já feita anteriormente

def Decomposition_LU(a,b):
  n = len(a)
  u = a
  l = np.eye(n)
  
  for k in range(0,n-1):
    for i in range(k+1,n):
        l[i][k] = a [i][k]/a[k][k]
        u[i][k] = 0
        for j in range(k+1, n):
          u[i][j] = u[i][j] - l[i][k]*u[k][j]
          
  return l, u

def resolSystem_TriAdapted(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(0,n):
      s=0
      for j in range(0,n-1):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x
  
def resolSystem_Tri(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(n-2,-1,-1):
      s=0
      for j in range(i+1,n):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x
  

a = np.array([[3.,-4.,1.],[1.,2.,2.],[4.,0.,-3.]])

n = len(a)

p = np.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
b= np.array([9.,3.,-2.])


a, p, b = pivoting(a,p,n,b)
print("\nMatriz final do pivoteamento:")
print(a)
l, u = Decomposition_LU(a,b)
print("\nMatriz L:")
print(l)
print("\nMatriz U:")
print(u)
y = resolSystem_TriAdapted(l,b)
print("\nY:")
print(y)
x = resolSystem_Tri(u,y)
print("\nX:")
print(x)

print("\n-----------------------------------------------")

print("\nPor questão de comparação, segue a resolução pelo linalg, a partir da matriz final do Pivoteamento:")
a = np.array([[ 4. , 0.  ,  -3.   ],[ 0.75,  -4.,     3.25 ],[ 0.25 , -0.5,    4.375]])
n = len(a)
print("\nMatriz Final:")
print(a)
b = np.array([-2. , 9.,  3.])
print("\nResolução do sistema:")
print(np.linalg.solve(a,b))



Matriz inicial:
[[ 3. -4.  1.]
 [ 1.  2.  2.]
 [ 4.  0. -3.]]

Matriz A do pivotemaneto
[[ 4.    0.   -3.  ]
 [ 0.25  2.    2.75]
 [ 0.75 -4.    3.25]]

Matriz A do pivotemaneto
[[ 4.     0.    -3.   ]
 [ 0.75  -4.     3.25 ]
 [ 0.25  -0.5    4.375]]

Matriz identidade Final:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Matriz b Final:
[-2.  9.  3.]

Matriz final do pivoteamento:
[[ 4.     0.    -3.   ]
 [ 0.75  -4.     3.25 ]
 [ 0.25  -0.5    4.375]]

Matriz L:
[[1.     0.     0.    ]
 [0.1875 1.     0.    ]
 [0.0625 0.125  1.    ]]

Matriz U:
[[ 4.         0.        -3.       ]
 [ 0.        -4.         3.8125   ]
 [ 0.         0.         4.0859375]]

Y:
[-2.0, 9.375, 1.953125]

X:
[-0.14149139579349906, -1.8881453154875718, 0.4780114722753346]

-----------------------------------------------

Por questão de comparação, segue a resolução pelo linalg, a partir da matriz final do Pivoteamento:

Matriz Final:
[[ 4.     0.    -3.   ]
 [ 0.75  -4.     3.25 ]
 [ 0.25  -0.5    4.375]]

Resolução d