In [0]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(M)
Final = M*A
print(Final)


[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [0]:
import numpy as np
def func( A,n ): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])

n = np.shape(A)[0] - 1
a,b = func(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print(np.dot(M,b))


[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]


In [1]:
import numpy as np

def Decomposition_LU(a,b):
  n = len(a)
  u = a
  l = np.eye(n)
  
  for k in range(0,n-1):
    for i in range(k+1,n):
        l[i][k] = a [i][k]/a[k][k]
        u[i][k] = 0
        for j in range(k+1, n):
          u[i][j] = u[i][j] - l[i][k]*u[k][j]
          
  return l, u

def resolSystem_TriAdapted(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(0,n):
      s=0
      for j in range(0,n-1):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x
  
def resolSystem_Tri(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(n-2,-1,-1):
      s=0
      for j in range(i+1,n):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x

def all_integrated(a,b):
  print("\nMatriz A: ")
  print(a)
  print("\nSolução de X Pelo Linalg:")
  resp = np.linalg.solve(a,b)
  print(resp)
  l, u = Decomposition_LU(a,b)
  print("\nMatriz L: ")
  print(l)
  print("\nMatriz U: ")
  print(u)
  y = resolSystem_TriL(l,b)
  print("\nLy = b" )
  print("Y=" )
  print(y)
  print("\nUx = y")
  print("X =")
  x_solverSystem = resolSystem_Tri(u,y)
  print(x_solverSystem)


  
  
a = np.array([[3.,(2.),(4.)], [1.,1.,(2.)], [(4.),(3.),(2.)]])
b = np.array([1.,2.,3.])


all_integrated(a,b)




Matriz A: 
[[3. 2. 4.]
 [1. 1. 2.]
 [4. 3. 2.]]

Solução de X Pelo Linalg:
[-3.  5.  0.]

Matriz L: 
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]

Matriz U: 
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -4.        ]]

Ly = b
Y=
[1.0, 1.6666666666666667, -4.440892098500626e-16]

Ux = y
X =
[-3.0, 5.0, 1.1102230246251565e-16]
